domain: simple-frontend.romanow-alex.ru
port: 3000

image:
  name: romanowalex/simple-frontend
  version: v1.0
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi